### ISSUE TITLE
Build on CentOS5.8

### ISSUE THREAD

**Issue by ysksuzuki** [cisco/openh264#2025]
Hi,
Can I build openh264 on CentOS5.8? I'm trying to build openh264 on CentOS5.8, but it failed with the error below.

```
codec/common/src/WelsThreadLib.cpp: In function ‘WELS_THREAD_ERROR_CODE WelsQueryLogicalProcessInfo(WelsLogicalProcessInfo*)’:
codec/common/src/WelsThreadLib.cpp:480: error: ‘CPU_COUNT’ was not declared in this scope
```

I also tried to apply the patch which the link below is mentioning to `codec/common/src/WelsThreadLib.cpp` and build, but it also failed with the error.  
http://www.redhat.com/archives/libvir-list/2012-August/msg01515.html 

```
nasm -DUNIX64 -f elf64 -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
nasm: fatal: unrecognised output format `elf64' - use -hf for a list
type `nasm -h' for help
```

Thank you in advance.

**Comment by ethanhugg** [comment]
I've built it on Fedora so it should build on CentOS.  My first guess is that your version of nasm is too old.  Try with version 2.11.06 of nasm.

**Comment by ysksuzuki** [comment]
@ethanhugg Thanks! My nasm version is too old. I could build openh264 with nasm 2.11.06. But the patch below was needed when I build it on CentOS5.8. Do you think that the patch is necessary? 

```
--- a/codec/common/src/WelsThreadLib.cpp
+++ b/codec/common/src/WelsThreadLib.cpp
@@ -466,6 +466,18 @@ WELS_THREAD_ERROR_CODE    WelsMultipleEventsWaitAllBlocking (uint32_t nCount,
   return WELS_THREAD_ERROR_WAIT_FAILED;
 }
 
+# ifndef CPU_COUNT
+static int CPU_COUNT(cpu_set_t *set) {
+  int i, count = 0;
+  for (i = 0; i < CPU_SETSIZE; i++) {
+    if (CPU_ISSET(i, set)) {
+      count++;
+    }
+  }
+  return count;
+}
+# endif /* !CPU_COUNT */
+
 WELS_THREAD_ERROR_CODE    WelsQueryLogicalProcessInfo (WelsLogicalProcessInfo* pInfo) {
 #ifdef ANDROID_NDK
   pInfo->ProcessorCount = android_getCpuCount();

```

**Comment by ethanhugg** [comment]
I believe CPU_COUNT first appeared in glibc 2.6 which was quite some time ago.  None of us have setups that old, but if this makes OpenH264 build and work for you then we would be happy to have a pull request from you with this patch.  Thanks.

**Comment by ysksuzuki** [comment]
@ethanhugg I see. I'll discuss the platforms which our product have to support. And then if it's needed, I'll send a pull request. Thanks!
